table 'Definition List Examples'
	lineageTag: fdfa122f-63a2-41bd-badf-d6c21c2bff4a

	column 'result type'
		dataType: string
		lineageTag: 54948bbb-669c-41bc-95a4-e0174f33e9ab
		summarizeBy: none
		sourceColumn: result type

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: 6bb65db6-b34a-4e8f-b72f-a43b46de0e76
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = User

	partition 'Definition List Examples' = m
		mode: import
		source =
				let
				  Quelle = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCk7MSS1W0lEyNDUxMjYy1DE0UorViVZyy6xQcM4vLgFJ6VoA5YwM9QxNwFJhiUWZiUk5qQh5UxMTIwtLHTNzsHxQaklpUR7ISCMTAyNjHSNDpdhYAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"result type" = _t, value = _t]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(Quelle,{{"value", type number}})
				in
				  #"Geänderter Typ"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

